"commit_message": "Fix: New translations %original_file_name% from Crowdin"
"append_commit_message": false

"files": [
  {
    "source" : "/_locales/en_US/messages.json",
    "translation" : "/_locales/%locale_with_underscore%/messages.json"
  }
]
