"commit_message": "Fix: New translations %original_file_name% from Crowdin"
"append_commit_message": false

"files": [
  {
    "source" : "/_locales/en/messages.json",
    "translation" : "/_locales/%two_letters_code%/messages.json"
  }
]
